/*
 * Copyright 2013 Thiago Uriel M. Garcia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.uriel.nm.server.view;

import java.io.Serializable;
import java.util.Locale;
import java.util.TimeZone;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ResourceBundleMessageSource;

/**
 * Abstract class used to provide default Managed Bean functionality, such as:
 * <ul>
 *      <li>Access to the logger instance, for console messages.</li> 
 *      <li>Message retrieval from <i>LoggerMessages</i> bundle.</li>
 *      <li>Message retrieval from <i>ApplicationMessages</i> bundle.</li>
 * </ul>
 * @author Thiago Uriel M. Garcia
 */
public abstract class AbstractManagedBean implements Serializable
{
    /** Serialization constant, automatically generated by JVM. */
    private static final long serialVersionUID = 4352063125953117813L;

    /** Logger instance able to send messages to console. */
    protected final Logger logger = LoggerFactory.getLogger(this.getClass());
    
    /** Spring object that provides I18N messages. */
    @Autowired
    private ResourceBundleMessageSource messages;

    /** 
     * Provides the current default {@link TimeZone}, that may be used for
     * all formatting needs in the application.
     * 
     * @return
     *      Current {@link TimeZone} used for the whole application.
     */
    public TimeZone getTimeZone()
    {
        return TimeZone.getDefault();
    }
    
    /** 
     * Provides the current default {@link Locale}, that may be used for
     * all formatting needs in the application.
     * 
     * @return
     *      Current {@link Locale} used for the whole application.
     */
    public Locale getLocale()
    {
        return Locale.getDefault();
    }
    
    /**
     * Provides a localized, formatted and localized message from bundles.
     * 
     * @param code  Message name in bundle.
     * @param args  Optional args for substitution in wildcards.
     * @return      Bundle message, correctly formatted and localized.
     */    
    protected String message(String code, String... args) 
    {
        return messages.getMessage(code, args, Locale.getDefault());
    }
}
