/*
 * Copyright 2013 Thiago Uriel M. Garcia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.uriel.nm.server.view;

import io.uriel.nm.server.business.SubscriptionServices;
import io.uriel.nm.server.business.model.Device;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

@Controller
@Scope("view")
public class SubscriptionsBean extends AbstractManagedBean 
{
    /** Serialization constant generated by JVM. */
    private static final long serialVersionUID = -8313831191353361482L;

    /** Current device ID, being managed by the UI. */
    private String currentDeviceId;
    
    /** Message that's going to be pushed to selected device.*/
    private String messageToPush;
    
    /** Service used to manage subscriptions. */
    @Autowired
    private SubscriptionServices subscriptionService;
    
    /**
     * Provides a <b>live</b> version of the current list of subscriptions.
     * 
     * @return
     *      An {@code Iterable} with all devices currently subscribed.
     */
    public Iterable<Device> getSubscriptions()
    {
        logger.debug("Requesting a live subscription list.");
        return subscriptionService.listDevices();
    }
    
    /** 
     * Cancels a subscription for a given device indentifier.
     * 
     * @param deviceId
     *      Identifier of the device that is going to be unregistered. 
     */
    public void unsubscribe(String deviceId)
    {
        logger.debug(message("log.unsubscribe.begin", deviceId));
        subscriptionService.unsubscribe(deviceId);
    }
    
    public void pushNotification()
    {
        logger.debug(message("log.notify.begin", currentDeviceId));
    }

    /**
     * Getter method for {@code currentDeviceId}.
     * @return Current value for {@currentDeviceId}.
     */
    public String getCurrentDeviceId() 
    {
        return currentDeviceId;
    }

    /**
     * Setter method for {@code currentDeviceId}.
     * @param currentDeviceId New value for {@code currentDeviceId}.
     */
    public void setCurrentDeviceId(String currentDeviceId) 
    {
        this.currentDeviceId = currentDeviceId;
    }

    /**
     * Getter method for {@code messageToPush}.
     * @return Current value for {@code messageToPush}.
     */
    public String getMessageToPush() 
    {
        return messageToPush;
    }

    /**
     * Setter method for {@code messageToPush}.
     * @param messageToPush New value for {@code messageToPush}.
     */
    public void setMessageToPush(String messageToPush) 
    {
        this.messageToPush = messageToPush;
    }
    
}
